# Generated by Django 6.0.6 on 2026-06-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='cle_api',
            field=models.CharField(blank=True, help_text="Utilisée pour l'accès en lecture à l'API (ex: Power BI). Laisser vide si non utilisée.", max_length=64, null=True, unique=True, verbose_name='Clé API'),
        ),
    ]
