# Generated by Django 6.0.6 on 2026-06-30 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0002_utilisateur_cle_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateurmensuel',
            name='frequentation_gratuite',
            field=models.PositiveIntegerField(default=0, verbose_name='Fréquentation gratuite'),
        ),
        migrations.AddField(
            model_name='indicateurmensuel',
            name='frequentation_payante',
            field=models.PositiveIntegerField(default=0, verbose_name='Fréquentation payante'),
        ),
        migrations.AlterField(
            model_name='sitetouristique',
            name='categorie',
            field=models.CharField(blank=True, choices=[('musee', 'Musée'), ('site_patrimonial', 'Site patrimonial'), ('office_tourisme', 'Office de tourisme'), ('parc_jardin', 'Parc / jardin'), ('monument', 'Monument'), ('site_naturel', 'Site naturel'), ('art_contemporain', "Lieu d'art contemporain"), ('autre', 'Autre')], max_length=30, verbose_name='Catégorie'),
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'événement")),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('frequentation', models.PositiveIntegerField(default=0, verbose_name="Fréquentation totale de l'événement")),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_saisis', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='suivi.sitetouristique')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
        ),
    ]
