# Generated by Django 6.0.7 on 2026-07-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0003_indicateurmensuel_frequentation_gratuite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeDeTourisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Office de tourisme',
                'verbose_name_plural': 'Offices de tourisme',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='sitetouristique',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='sites', to='suivi.officedetourisme', verbose_name='Offices de tourisme rattachés'),
        ),
    ]
